### ISSUE TITLE
Schedule raw bytes

### ISSUE THREAD

**Issue by vladyspavlov** [twhittock/avatto_me167#1]
Hi,
I want to help you. Can you provide wireshark log or raw bytes values sent by TRV? It's will be much easier to understand how it works.
Thanks!
https://github.com/twhittock/avatto_me167/blob/40c32f9e3ca9e2c96be4fbce5f62427938b75406/me167.js#L38-L43

**Comment by twhittock** [comment]
Hi. Thanks for the offer, I don't have any raw data for that message, as I don't use it. Since the TRV is being controlled via zigbee2mqtt and home assistant, there's really no need for an on-device schedule in my opinion.

The schedule code came from the original source of this converter here: https://github.com/Koenkk/zigbee2mqtt/issues/13727 

That said, if you do use it, and have a better implementation of the schedule code, I'm more than happy to include your work here. I'll leave the issue open and if anyone who owns the device wants to contribute any information for someone to work on the schedule then that'd be great!

Thanks.

**Comment by rickx** [comment]
I think it might be important. One of my devices seems to come with its schedule. Or some manual procedure I did created it. Such a schedule then obviously interferes with the automation logics you place on top in OH. So, unless there is another manual procedure to remove existing schedules, being able to change the existing one would be useful in my case.

**Comment by twhittock** [comment]
That's just a matter of switching the mode to heat.

**Comment by rickx** [comment]
so you're saying in heat mode the schedule will not trigger anything. Is that tested?

**Comment by twhittock** [comment]
Yeah that's how I run mine
